### ISSUE TITLE
[Realme GT Neo2] Volume steps unchanged on Android 12 / Realme UI 3.0

### ISSUE THREAD

**Issue by mmetharam** [Magisk-Modules-Alt-Repo/audio-misc-settings#1]
Hello, I recently updated my phone, the Realme GT Neo2, to android 12 (RUI 3.0) and the magisk module doesn't manage to change the volume steps anymore. The rest of the module's functionalities seem to work just fine as i do notice a sound difference between flashing and not flashing the mod, but the volume steps remain unchanged.

However this worked just fine when I was still on android 11 (so Realme UI 2.0); any advice on this? Or any way I can help to fix this?

**Comment by yzyhk904** [comment]
I think Realme improved the audio volume framework in an AOSP-incompatible way. My module has been made compatible to AOSP (A8.1, A9, A10, A11 and A12) including LineageOS, and the volume steps feature of crDroid & Blissrom (A9, A10, A11) and others.

If you flash a GSI ROM on your device, you could use the 100 volume steps feature of my module.

By the way, if you use my root script "USB_SampleRate_Changer", you can avoid DRC (compression) imposed on your device. And I recommend to use "jitter-reducer.sh" in the extra folder of the script.

**Comment by mmetharam** [comment]
I see, it's just a strange thing since the mod worked well on android 11. I was hoping there was some kind of universal fix or something haha but i guess it's a RIP for now.
