### ISSUE TITLE
[OOT] How do I print the current jitter in Terminal?

### ISSUE THREAD

**Issue by HarriBuh** [Magisk-Modules-Alt-Repo/audio-misc-settings#15]
While I appreciate all the codes that came with the Readme, I couldn't find a single code for **displaying the current jitter while playing audio,** similar to the "ping" code on windows. The www couldn't help me either.

**Comment by yzyhk904** [comment]
You can see the jitter while playing audio by "extras/dumpsys-filtered.sh", but I think it isn't similar to "ping".
Jitter is the standard deviation of actual sampling frequency or its converted value in time but isn't any latency.
