### ISSUE TITLE
[BUG] Audio misc.settings simply broke my equalizer

### ISSUE THREAD

**Issue by KpuCko** [Magisk-Modules-Alt-Repo/audio-misc-settings#16]
When Audio misc.settings module is installed (even the latest version) when I click on equalizer the screen simply crashes.

**To Reproduce**
1. Go to 'Open Fox's Mmm'
2. Click on 'Go to Online, select Audio misc.settings module'
3. Scroll down to 'Install and reboot'
4. Try to open Equalizer in Settings menu

**Expected behavior**
For sure it was working on a fresh image (without Magisk and FoxMmm installed)

**Screenshots**
Screen crashed, no screenshots

**Device info(please complete the following information):**
 - Device: Xiaomi Mi10 #umi
 - OS: MIUI by xiaomi.eu v.14.0.3.0TJBCNXM
 - 2.1.1

**Comment by yzyhk904** [comment]
This isn't any bug. The module disables the effects framework interfacing to system wide equalizers. Please read README.md.

Most equalizers don't function only without crashing , but some crash because they don't confirm the existence of the framework.

**Comment by KpuCko** [comment]
> You can uninstall it as usual in the Magisk manager.

Yes, I already mentioned this above, uninstalled but the equalizer still crashes.

**Comment by yzyhk904** [comment]
No, you didn't uninstall the module as usual! What did you do in the Magisk manager?
My module will revert back your device after deleting it and rebooting in the Magisk manager.

**Comment by KpuCko** [comment]
There is not much things to do, just clicked on the uninstall button.

**Comment by yzyhk904** [comment]
There's a "REMOVE" icon in every module field in the Magisk manager. Click the icon of the module, then reboot your phone. Please read "README" of the Magisk manager!

**Comment by KpuCko** [comment]
I have uninstalled it by using FoxMmm manager. Checked Magisk few seconds ago and it is not listed in the modules list.
So I assume it is removed. Whether or not removed, the original configuration is not restored in any way.

This conversation is not productive for me anymore, so I'm unsubscribing.
Thanks for your support.

A life advice - when something works, don't fix it.

**Comment by yzyhk904** [comment]
My module only changes a property "ro.audio.ignore_effects" temporally at every boot time. So your phone should revert back to its original state if you clicked the "REMOVE" and rebooted your phone

Why not reboot your phone?

A life advice: reboot your phone any way!
