### ISSUE TITLE
Number of steps in media volume don't change on OnePlus 9/10 Pro

### ISSUE THREAD

**Issue by BoGnY** [Magisk-Modules-Alt-Repo/audio-misc-settings#17]
Hi, I've always used this module on OnePlus 6 and 6T.

After upgrading my phones, the number of steps in media volume doesn't change, it remains the default.

**Comment by yzyhk904** [comment]
Do you use stock OSes on your phones?  Some stock OSes have modified the volume framework and become to be not compatible with that of AOSP which my module is targeting.

I think you can use my module if you install a popular custom ROM based on AOSP.

**Comment by BoGnY** [comment]
Yes I use latest OxygenOS on all devices
