### ISSUE TITLE
[FEATURE REQUEST] High Performance Mode for Qualcomm Dacs

### ISSUE THREAD

**Issue by theduffster** [Magisk-Modules-Alt-Repo/audio-misc-settings#18]
Hi,
I just wanted to run this by you since you seem to be more on top of Android audio then anyone these days and was wondering if you were aware of High Performance Mode in Qualcomm Dacs. What do you think of this:

https://github.com/oiakera/high_perf_dac/issues/11#issuecomment-1779805058

Looking at the source code, the description "enable/disable class AB config for hph" definitely doesn't reveal much, so mysterious...

It looks like high performance mode enables these parameters:

```
WCD9XXX_CLSH_STATE_HPHR,
WCD9XXX_CLSH_REQ_ENABLE,
WCD9XXX_CLSH_EVENT_PRE_DAC)
```

I was hoping you may have some insight into what these parameters actually do, and what High Performance Mode actually does.

I'm also not sure if this works on newer phones, looking through newer phone source code I have yet to see "high_perf_mode" as an option in [WCD9335](https://www.qualcomm.com/products/internet-of-things/consumer/audio/mobile-audio/wcd9335)+ phones. Still, Qualcomm says on their own website "High Performance Audio Playback" exists all the way up to the [9385](https://www.qualcomm.com/products/internet-of-things/consumer/audio/mobile-audio/wcd9385).

**Comment by theduffster** [comment]
Thank you for the reply. So when you tried these mods, could you confirm they were actually working as intended? I'm curious if anyone has actually gotten high performance mode to activate on a newer dac.

**Comment by yzyhk904** [comment]
I don't know they would work as intended or not, but just compared the hearable differences between before and after installing them. And I have a few interest for internal Dacs. Try external DACs and bluetooth devices.

Anyway I think jitter is crucial for audio experiences and analogue circuits are lesser important.
