### ISSUE TITLE
there is no SBC Dual channel mode with increased bitrate

### ISSUE THREAD

**Issue by nnnikolay-art** [Magisk-Modules-Alt-Repo/audio-misc-settings#24]
Everything works great in this module, but there is no increased SBC bitrate in Dual channel mode. OS LineageOS 21 (Android 14)

**Comment by yzyhk904** [comment]
LineageOS supports the SBC dual channel mode only for ver. 16.1 and 18.1. And as far as I know, there isn't any ROM supporting the mode since Android 13.

If you want the mode, use LineageOS ver. 18.1.

**Comment by nnnikolay-art** [comment]
Thank you. It's strange why these features were not merged into new versions
