### ISSUE TITLE
Bootloop on Android 14 

### ISSUE THREAD

**Issue by NMBlanco** [Magisk-Modules-Alt-Repo/audio-misc-settings#25]
The recent version of this module got me into a bootloop after installing.
Luckily I got out of it with some Safe Mode trick, but took me some hours to figure it out since there's no TWRP for my device.

My device: Motorola Edge 30 Ultra, Android 14, stock rom.
Latest magisk kitsune installed.

**Comment by yzyhk904** [comment]
I think this module cannot install on kitsune magisk because of no magisk-mirrors without "compatible Magisk-mirroring". What was you doing?

FYI, kitsune magisk has lost magisk-mirrors since mid February, and this module cannot install on it since then.

**Comment by NMBlanco** [comment]
I just installed the module and rebooted. Then got into the bootloop. Not even bootloop, it was just stuck at the Logo before the bootanimation comes in.

**Comment by yzyhk904** [comment]
This module is made to abort its installation when detecting no mirrors, i.e. Kitsune Magisk!  This happens here on the latest Kitsune Magisk.

Didn't you see its abort message? Kitsune Magisk manager should deny its installation even though you expect it.

How did you install this module? Using Kitsune Magisk manager? Androidacy magisk manager? or else?
