### ISSUE TITLE
Just question

### ISSUE THREAD

**Issue by mikropsoft** [Magisk-Modules-Alt-Repo/audio-misc-settings#27]
Hello @yzyhk904 

I'm a bit confused, so I wanted to open an issue regarding one of your repositories. The explanations on your modules are overly detailed and complex, and I would like to ask for your recommendation to get the best results. For instance, in the description section for this module, it was suggested to install another module. Besides these two modules, would other modules be effective for sound, or should they not all be used together? I don't want any conflicts.

(By the way, I didn't like the range increase of the volume in this module. If you could tell me the location of the code where this is implemented, I would like to adjust it myself.)

**Comment by yzyhk904** [comment]
If you are a casual music lover, install this module and [Audio jitter silencer](https://github.com/Magisk-Modules-Alt-Repo/audio-jitter-silencer) together.

If you are an audiophile expert, install [Hifi maximizer](https://github.com/yzyhk904/hifi-maximizer-mod) and the Audio jitter silencer together. Then use my root script [USB SampleRate Changer](https://github.com/yzyhk904/USB_SampleRate_Changer) for changing the sample rate of your DAC appropriately.

And I think a 0.5dB step volume control is needed for audiophiles. As you feel its inconvenience, you can use " long press" for step acceleration and also a volume GUI.

**Comment by mikropsoft** [comment]
Thanks sir!
