### ISSUE TITLE
Magisk-Mirrors Issue

### ISSUE THREAD

**Issue by theovit** [Magisk-Modules-Alt-Repo/audio-misc-settings#28]
When attempting to install this module, it displays the message: "The installation is aborted because no Magisk mirrors are found." It advises using the official Magisk app or installing a compatible Magisk module. However, upon installing the compatible Magisk module, it indicates that Magisk mirrors are found.

```
- Current boot slot: _a
- Device is system-as-root
**********************
 Audio misc. settings 
 by zyhk 
**********************
*******************
 Powered by Magisk 
*******************
- Extracting module files
  ***
  Aborted by no Magisk-mirrors:
    Try again
      a.) with official Magisk (mounting mirrors)
      b.) after installing "compatible Magisk-mirroring" Magisk module
  ***
```

```
- Copying zip to temp directory
- Installing magisk-module-compatible-magisk-mirroring-v1.1.3.zip
- Current boot slot: _a
- Device is system-as-root
Archive:  /data/user/0/ao.exdd/cache/flash/install.zip
  inflating: module.prop
*****************************
 Compatible Magisk-mirroring 
 by zyhk 
*****************************
*******************
 Powered by Magisk 
*******************
Archive:  /data/user/0/ao.exdd/cache/flash/install.zip
  inflating: customize.sh
- Extracting module files
Archive:  /data/user/0/ao.exdd/cache/flash/install.zip
  inflating: changelog.md
  inflating: customize.sh
  inflating: LICENSE
  inflating: module.prop
  inflating: mounting-compatible-magisk-mirrors.sh
  inflating: README.md
  inflating: uninstall.sh
  ***  Aborted: found the compatible Magisk-mirroring! ***
! Installation failed
```

**Phone**

Build AP2A.240605.024
Pixel 8 Pro 
Stock
Rooted

**Magisk**

App Version 27.0 (27000) 
Zygisk Yes
Ramdisk Yes

**Comment by yzyhk904** [comment]
First of all, your Audio misc settings module is rather old. Use the latest (v1.3.7)!

As both modules shares the same checking code for Magisk mirrors, you could install the Audio misc module at this stage. Although I don't know how and what you have done till  then.

**Comment by yzyhk904** [comment]
Uum, isn't it some MRepo issue?

Did you reboot just after installing "compatible Magisk-mirroring"? Magisk needs reboot to execute its modules. Module installation doesn't complete until next booting-up.

**Comment by yzyhk904** [comment]
I understand your reading. I think also this issue is caused by some repo managers' fault.
