### ISSUE TITLE
 problems on nothing phone (2)

### ISSUE THREAD

**Issue by maxsspeaker** [Magisk-Modules-Alt-Repo/audio-misc-settings#30]
After installing the module, the volume display on the rear panel stops working correctly (glyph) 
Also, music visualization on the back of the panel does not work...
If you remove the module, everything starts working fine again 

I don't know if you can fix it, but if you can fix it, I will be very grateful to you

**Comment by yzyhk904** [comment]
It's a main feature ("disabling the effects framework"). Since visualizers and music listeners use the effects framework, they cannot work at all.
