### ISSUE TITLE
Issues on Galaxy Tab S8

### ISSUE THREAD

**Issue by innit86** [Magisk-Modules-Alt-Repo/audio-misc-settings#31]
Does not work properly on Samsung Galaxy Tab S8 with Android 14. After flashing sound plays at full blast even on the lowest volume level. It's so loud that it almost breaks the speaker. Also 100 volume steps are missing.

[magisk_install_log_2024-07-27T17.35.13.txt](https://github.com/user-attachments/files/16400752/magisk_install_log_2024-07-27T17.35.13.txt)

Galaxy Tab S8+
Android 14
Magisk Canary 27.0 (27006) (0495468d)
Compatible Magisk-mirroring1.1.3

**Comment by yzyhk904** [comment]
I guess you are using a stock ROM. It's an issue of the ROM.

I think if you install an GSI ROM, then you could use my module properly.

**Comment by innit86** [comment]
> I guess you are using a stock ROM. It's an issue of the ROM.
> 
> I think if you install an GSI ROM, then you could use my module properly.

Yes, stock OneUI Android 14. It worked fine on Android 12 but it seems like A14 breaks something. Can anything be done about it apart from installing GSI ROM?

**Comment by yzyhk904** [comment]
Uum, how about deleting a line specifying the 100 step in the ZIP file of this module?

The line ("ro.config.media_vol_steps=100") exists in "system.prop" file of the ZIP. Try deleting the line and installing (updating)  its modified ZIP over already installed one.

**Comment by innit86** [comment]
> Uum, how about deleting a line specifying the 100 step in the ZIP file of this module?
> 
> The line ("ro.config.media_vol_steps=100") exists in "system.prop" file of the ZIP. Try deleting the line and installing (updating) its modified ZIP over already installed one.

No change. Volume still at full blast on the lowest level.


- Copying zip to temp directory
- Installing magisk-module-audio-misc-v1.3.8-1-mod.zip
- Device is system-as-root
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
**********************
 Audio misc. settings 
 by zyhk 
**********************
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh
*******************
 Powered by Magisk 
*******************
- Extracting module files
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: LICENSE
  inflating: README.md
  inflating: changelog.md
  inflating: customize-functions.sh
  inflating: customize.sh
  inflating: module.prop
  inflating: post-fs-data.sh
  inflating: service.sh
  inflating: system.prop
  inflating: system.prop-workaround
  inflating: uninstall.sh
- Replace target: /system/vendor/lib/libalsautils.so
touch: /data/adb/modules_update/audio-misc-settings/system/vendor/lib/libalsautils.so/.replace: Not a directory
/data/user/0/com.topjohnwu.magisk/cache/flash/update-binary: line 606: can't create /data/adb/modules_update/audio-misc-settings/system/vendor/lib/libalsautils.so/.replace: nonexistent directory
chmod: /data/adb/modules_update/audio-misc-settings/system/vendor/lib/libalsautils.so/.replace: Not a directory
touch: /data/adb/modules_update/audio-misc-settings/system/vendor/lib64/libalsautils.so/.replace: Not a directory
- Replace target: /system/vendor/lib64/libalsautils.so
/data/user/0/com.topjohnwu.magisk/cache/flash/update-binary: line 606: can't create /data/adb/modules_update/audio-misc-settings/system/vendor/lib64/libalsautils.so/.replace: nonexistent directory
chmod: /data/adb/modules_update/audio-misc-settings/system/vendor/lib64/libalsautils.so/.replace: Not a directory
- Done

**Comment by yzyhk904** [comment]
By the way, are you using Official Magisk and its own manager? If so, I have no idea yet.

**Comment by innit86** [comment]
> By the way, are you using Official Magisk and its own manager? If so, I have no idea yet.
> 
> Edit: Sorry. you are using Magisk canary. Try Official Magisk once!

Magisk Canary 27.0 (27006) official from topjohnwu
