### ISSUE TITLE
Module breaks volume controls.

### ISSUE THREAD

**Issue by pchelkk** [Magisk-Modules-Alt-Repo/audio-misc-settings#32]
For some reason module breaks volume controls. It's still 6% per step and if I go past 12% I don't get any sound. Device: Redmi note 12 pro 5g, using xiaomi.eu based on hyperos 1.0.6.0 CN. 

Upd: so after getting rid of everything volume steps related in module files it works fine.

**Comment by yzyhk904** [comment]
It's a bug of HyperOS. 

You can probably use the 100 volume step by its GUI bar, but cannot by a volume button.
If you install a custom ROM, you could use the volume step correctly.
