### ISSUE TITLE
Does this also affect the mic?

### ISSUE THREAD

**Issue by erickmufath** [Magisk-Modules-Alt-Repo/audio-misc-settings#33]
Does it also affect how the mic works?

**Comment by yzyhk904** [comment]
Feature request? Or Did anything happen?

**Comment by erickmufath** [comment]
I understand. At first I just wanted to ask. But yes, That's a good idea, after all it's still related to audio. If you are curious, I will explain a little, when recording sound, the sound produced is not very clean, in quiet conditions there is no problem with the mic if I don't make a sound, there is no buzzing or static noise, but when I start making sound it is there. Btw I am using a mediatek device. Thank you for your attention.

**Comment by yzyhk904** [comment]
Are you trying to record calls? This module disables all effects including automatic gain control and echo cancelation.

**Comment by erickmufath** [comment]
@yzyhk904 No, I'm trying to record my singing. Only when I start making noise, noise can also be heard, although it is not dominant.

**Comment by erickmufath** [comment]
If this is possible to fix, it might be better to create a separate module, just my opinion. Thanks.

**Comment by yzyhk904** [comment]
Isn't this caused by your app or OS? I think there's no cause in my module.

**Comment by erickmufath** [comment]
> Isn't this caused by your app or OS? I think there's no cause in my module.

The first answer I'm not sure, the second answer I don't mean that, there is indeed a problem with the sound when installing this module which sometimes the speaker doesn't make any sound and the sound quality becomes low, but the problem I'm experiencing is not that caused by the module. Let me explain from the beginning. First, I want to ask about this module, does it have any effect on the mic or not? and you label it with "feature request". From here I think it seems like this module does not affect the way the mic works. Then I agreed to the proposal and explained a little about the problem I was experiencing, maybe you can help.

**Comment by yzyhk904** [comment]
I guessed automatic gain control or echo cancelation effect (usually used in telephone communication tools) affected something to your app, but you are negative. Then, I have no call to mind and no idea now.

**Comment by erickmufath** [comment]
> I guessed automatic gain control or echo cancelation effect (usually used in telephone communication tools) affected something to your app, but you are negative. Then, I have no call to mind and no idea now.

I apologize if there are any words that are not pleasing to you. I am just looking for a solution, It seems that this module is not compatible with my device for audio output, so it doesn't matter. What I want is the audio input problem that has been explained to be solved, this is also what made me suggest to create a separate module about this. Respectfully i try to be polite, I used a translation tool to write this, I didn't mean anything. Just close this if you're bothered by me.

**Comment by erickmufath** [comment]
If there really is no idea whatsoever, then that's okay. It's not your obligation to fulfill my wishes.

**Comment by yzyhk904** [comment]
What I cannot understand is where the separate module came from? And I think the problem is caused by your app or OS. My module cannot affect something to inputs except via such effects.

I guess disabling effects framework by my module makes an untested situation where your app or OS issues such problems. But it's a fault of your app or OS.

**Comment by erickmufath** [comment]
> What I cannot understand is where the separate module came from? And I think the problem is caused by your app or OS. My module cannot affect something to inputs except via such effects.
> 
> I guess disabling effects framework by my module makes an untested situation where your app or OS issues such problems. But it's a fault of your app or OS.

From your idea if any. I am not talking about making a separate module from this module, but making a separate(new module) based on the problem that has been explained (not merge/combined with this module). I don't think this problem is from my app, it would be strange if it only happens on my device. But ok, if the problem is with my OS, then why does every rom I run experience the same thing, even the default OS too. And if the problem is really from the OS, then the module seems to be able to solve it, but I don't understand anything about it.

**Comment by yzyhk904** [comment]
Making the separate module is your own task, not mine.

Disabling the effects framework is a main feature of this module, so it means you cannot use this module on the device.

Many OS and apps appear faults because of their bugs when using this module. For example, HyperOS cannot handle 100 steps volume properly, crashes sound settings, and even rebooted when connecting a USB DAC. Some sound apps crashes  because of their bug which isn't able to handle a situation of the effects framework disabled.

**Comment by erickmufath** [comment]
@yzyhk904 I agree, that's why I asked a separate module, if you dont mind. If you mind i respect it. I also said before that it is not an obligation, but you keep confuse me. It's ok, maybe my english is not that good, i will end this if that's your answer. Thank you for your time.

**Comment by yzyhk904** [comment]
I think you are confused. Another module isn't any feature request!
