### ISSUE TITLE
Keep effects framework

### ISSUE THREAD

**Issue by yabo-boye** [Magisk-Modules-Alt-Repo/audio-misc-settings#36]
Is it possible to benefit from this module while keeping the effects framework active? 

The reason for it would be to use jamesdso convolver and eq system wide, as the rootless version does bot work in lineage 14

Also, do you know a way to have separate audio volume per app on aosp ROMs like lineage os?

Thank you

**Comment by yzyhk904** [comment]
Never!

I believe disabling effects framework is the best equalizing. Almost all people must be using equalizers for compensating to side effects of the effects framework and re-sampling distortion.

**Comment by yabo-boye** [comment]
Cool, thank you. I use convolution mainly for manipulating the stereo image in my car.

As for the second question above, I would appreciate any insights.

**Comment by yzyhk904** [comment]
I don't know. Why not install LineageOS?

**Comment by yabo-boye** [comment]
I have lineage os.
The thing with the stereo image is to have it tilted 45 degrees since im closer to the left speaker while driving.

I love your modules otherwise,  real improvement in my audio experience.

**Comment by yzyhk904** [comment]
I understand your situations. I'm also using equalizing for suppressing standing waves in a pre-amp.

I think the effects framework of Android is very harmful. It's better to use equalizing in a pre-amp or even  in an music app if you can.
