### ISSUE TITLE
All steps above 15 are silent, first 15 are the same as before

### ISSUE THREAD

**Issue by sdaly31** [Magisk-Modules-Alt-Repo/audio-misc-settings#38]
After installing this module my first 15 volume steps are as before, from nothing to max. Then I can go through the other 85 steps but they are all silence. I am running android 13 stock on the unihertz jelly star. Please let me know if I can provide any other information or logs to help.

**Comment by yzyhk904** [comment]
Your phone isn't compatible with the AOSP volume control. And Stock ROMs aren't supported.
