### ISSUE TITLE
Do you recommend this module for external USB DAC?

### ISSUE THREAD

**Issue by MirceaMx** [Magisk-Modules-Alt-Repo/audio-misc-settings#6]
Do you recommend this (or other of your modules) module for DD HiFi TC35B 2021 (external DAC) ?

Sorry, there was no way to PM

**Comment by yzyhk904** [comment]
I don't know this DAC, but entry class DAC's usually adopt an interface chip communicating with the adaptive mode or the synchronous one defined in the USB audio standard. As in these modes an Android host controller sends audio sampling rate clock signals to the DAC, the jitter generated at the host side affects the audio quality of the DAC tremendously.

Please follow the description of disabling battery optimizations in README.md. And also see "extras/jitter-reducer.sh" in [USB_SampleRate_Changer](https://github.com/yzyhk904/USB_SampleRate_Changer).

**Comment by MirceaMx** [comment]
The adapter DAC is a Realtek ALC5686 well tuned IMO (not a noob) . As for the device I'm using is a Sony Xperia 5 II - Snapdragon 865 - Android 12 . Not using your module atm but cause I thought using an external DAC (own sound processing) there would be no need. When I did use it I modified the volume steps from 100 to 40. Hope you find this helpful. Thanks!

**Comment by yzyhk904** [comment]
I think you aren't aware of audio equipment classes. The DAC must be using the adaptive mode or the synchronous one. You can see it by opening "/proc/asound/card1/stream0" on your phone while playing music. Please see a word in parentheses at "Endpoint:" lines; "SYNC", "ADAPTIVE" or "ASYNC" means that your DAC uses "synchronous", "adaptive" or "asynchronous" mode to communicate to your phone, respectively. The "asynchronous" mode is the best for audio use and usually adopted by more than $80 class DAC's.

Phones using SDM865 apply DRC (Dynamic Range Control, or shortly compression) on all audio outputs (including digital ones) and generate considerable jitter distorting digital audio outputs, especially for entry class DAC's as they are. 

I think experienced audio users want a volume of 0.5dB per step at least.

**Comment by MirceaMx** [comment]
Thank you! Saving your post for future reference.

**Comment by MirceaMx** [comment]
Closed (I need to get a better DAC)
