### ISSUE TITLE
low speaker volume?

### ISSUE THREAD

**Issue by yaoberh** [Magisk-Modules-Alt-Repo/audio-misc-settings#7]
Hey! 
Is it normal for the max volume to be much lower than without the module?
Can I do something about it?
Thanks a bunch

**Comment by yzyhk904** [comment]
I've never heard such things till now, but I guess that you use a much enhanced stock ROM which isn't compatible with the AOSP ROM. I think you could use the module normally if you installed a popular GSI or custom ROM.

**Comment by yaoberh** [comment]
Stock rooted A12 rom. It's very strange. Doesn't happen with headphones, only with the speaker. Also tried external speakers and they don't have the problem either :/
