### ISSUE TITLE
Feature Request: Undo script

### ISSUE THREAD

**Issue by MikaelaMuller** [Magisk-Modules-Alt-Repo/audio-misc-settings#8]
Hello, i tried out this module to see if it'll improve the audio performance of my device and well it didn't really seem like it did for me and it also made JamesDSP not work anymore even after installing. Please give us a a way of reversing the changes this made on our devices, thank you.

**Comment by yzyhk904** [comment]
Didn't you uninstall this module in the Magisk manager and reboot? Then this module will revert your device to its previous state automatically. If you use crDroid or else having the volume steps feature, you need an extra reboot to populate its reverted property. This module changes only properties initialized in the boot process except the volume steps property (that will be reverted in the uninstallation).

I think disabling the effect framework (interfacing with equalizers and others) is the best for hi-fi audio quality. The effect framework generates large jitter making foggy sound like distortion especially for bluetooth earphones.
